### ISSUE TITLE
메인화면 - 새로운 루트 기록

### ISSUE THREAD

**Issue by ddanglehee** [today-route/today-route-android#1]
## 🗒 Tasks
**위치 권한이 허가되어있지 않은 경우**
- [x] 위치 권한을 허가한다.

**'루트 기록 시작' 버튼을 누를 경우** 
- [x] '루트 기록 시작' 버튼의 text가 '루트 기록 종료'로 바뀐다.
- [x] 버튼을 누른 시점의 시간을 기록한다.
- [x] 지도를 사용자의 현재 위치 지점으로 이동시킨다.
