### ISSUE TITLE
홈화면, 새 루트 추가 화면

### ISSUE THREAD

**Issue by ddanglehee** [today-route/today-route-android#24]
## 🗒 Tasks
- [ ] 홈화면에서 연인 정보 띄우기
- [ ] 새 루트 추가 화면 UI 만들기
- [ ] 새 루트 추가 화면 로직 뼈대 만들기 (TODO로)
