### ISSUE TITLE
로컬환경에서 서버 구동

### ISSUE THREAD

**Issue by ddanglehee** [today-route/today-route-android#31]
## 🗒 Tasks
- [x] node.js 설치
- [x] today-route server에 있는 코드 받기
- [x] 서버와 통신하는 부분 수정해서 잘 동작하는지 확인
