### ISSUE TITLE
모듈 분리

### ISSUE THREAD

**Issue by ddanglehee** [today-route/today-route-android#9]
## 🗒 Tasks
- [x] buildSrc 모듈 생성
- [x] data 모듈 생성
- [x] 클린 아키텍처 공부 <- (domain 모듈도 생성할지 고민)
